[Service]
Host = "edgex-device-modbus"
Port = 49999
ConnectRetries = 3
Labels = []
OpenMsg = "device modbus started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Logging]
EnableRemote = true
File = "./device-Modbus.log"

[Writable]
LogLevel = "INFO"

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

# Pre-define Devices
[[DeviceList]]
  Name = "Modbus-TCP-test-device-RPI"
  Profile = "Test.Device.Modbus.Profile-RPI"
  Description = "RPI test"
  labels = [ "Air conditioner","modbus TCP" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.modbus-tcp]
       Address = "192.168.1.83"
       Port = "502"
       UnitID = "1"
  [[DeviceList.AutoEvents]]
    Frequency = "20s"
    OnChange = false
    Resource = "Switch"

